apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinelops-config
  namespace: sentinelops
data:
  APP_ENV: production
  API_PORT: "8080"
  REDIS_ADDR: sentinelops-redis:6379
  AUTH_ENABLED: "false"
  KEYCLOAK_ISSUER_URL: http://keycloak.sentinelops.svc.cluster.local:8080/realms/sentinelops
  KEYCLOAK_CLIENT_ID: sentinelops-web
  NEXT_PUBLIC_API_BASE_URL: http://sentinelops-api:8080/api/v1
