apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinelops-postgres
  namespace: sentinelops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinelops-postgres
  template:
    metadata:
      labels:
        app: sentinelops-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: sentinelops-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sentinelops-postgres
  namespace: sentinelops
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: sentinelops-postgres
