apiVersion: v1
kind: Secret
metadata:
  name: sentinelops-secret
  namespace: sentinelops
type: Opaque
stringData:
  POSTGRES_DB: sentinelops
  POSTGRES_USER: sentinelops
  POSTGRES_PASSWORD: sentinelops
  DATABASE_URL: postgres://sentinelops:sentinelops@sentinelops-postgres:5432/sentinelops?sslmode=disable
