apiVersion: v1
kind: Secret
metadata:
  name: sentinelops-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.postgres.database }}"
  POSTGRES_USER: "{{ .Values.postgres.username }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  DATABASE_URL: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@sentinelops-postgres:5432/{{ .Values.postgres.database }}?sslmode=disable"
